In [1]:
import os
os.environ['HSA_OVERRIDE_GFX_VERSION'] = '10.3.0'

import torch
print(torch.cuda.is_available())

False


# Input

In [2]:
raw_dummy = torch.tensor(
    [
        [
            -17.45557857, 2.174657688, 2.367182984, -16.99430584, -31.52132607,
        ],
        [
            -13.55773965, 1.965214473, -47.67187483, -5.831726978, -55.39959188,
        ],
        [
            -2.178412257, 9.753551178, -14.56978835, -76.58151401, -30.69740492,
        ],
        [
            -43.89739173, -50.37969167, -32.77935361, -66.49576026, -6.412497726,
        ],
        [
            -10.70635018, -72.22502322, -26.17916214, 1.4530419, 8.722773095,
        ],
        [
            -24.66762607, -18.16726717, 7.208516509, -13.64334883, -2.652998327,
        ],
    ]
)

In [3]:
raw_dummy_mean = torch.mean(raw_dummy, 0)
raw_dummy_std = torch.std(raw_dummy, 0, correction=0)

print(raw_dummy_mean)
print(raw_dummy_std)

tensor([-18.7439, -21.1464, -18.6041, -29.6823, -19.6602])
tensor([13.1362, 30.2911, 19.2597, 30.3075, 21.6416])


In [4]:
normal_dummy = (raw_dummy - raw_dummy_mean) / raw_dummy_std
print(normal_dummy)

tensor([[ 0.0981,  0.7699,  1.0889,  0.4186, -0.5481],
        [ 0.3948,  0.7630, -1.5093,  0.7870, -1.6514],
        [ 1.2611,  1.0201,  0.2095, -1.5474, -0.5100],
        [-1.9148, -0.9651, -0.7360, -1.2147,  0.6121],
        [ 0.6119, -1.6863, -0.3933,  1.0273,  1.3115],
        [-0.4509,  0.0984,  1.3402,  0.5292,  0.7859]])


# Vertical frontend

In [5]:
i_v = normal_dummy.detach().clone()
print(i_v)

tensor([[ 0.0981,  0.7699,  1.0889,  0.4186, -0.5481],
        [ 0.3948,  0.7630, -1.5093,  0.7870, -1.6514],
        [ 1.2611,  1.0201,  0.2095, -1.5474, -0.5100],
        [-1.9148, -0.9651, -0.7360, -1.2147,  0.6121],
        [ 0.6119, -1.6863, -0.3933,  1.0273,  1.3115],
        [-0.4509,  0.0984,  1.3402,  0.5292,  0.7859]])


# Horizontal frontend

In [12]:
mpool = torch.nn.AvgPool2d(kernel_size=(1,5), stride=1, padding=0)
i_h = mpool(normal_dummy.detach().clone())
print(i_h)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got -3)